name: Generate Snake Animation

on:
  schedule:
    # Executa uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verifica o repositório
      - uses: actions/checkout@v3

      # Configura o Git para fazer merge automático durante o pull
      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config pull.rebase false

      # Atualiza o branch main local com as mudanças do remoto
      - name: Pull latest changes
        run: git pull origin main

      # Gera o arquivo SVG da animação da cobra
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Adiciona os arquivos gerados
      - name: Add generated files
        run: git add dist/

      # Commit dos arquivos gerados
      - name: Commit changes
        run: git commit -m "Update snake animation"

      # Push para o branch principal
      - name: Push changes
        run: |
          git push origin main

