name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Puxe as últimas mudanças do branch principal
      - name: Pull latest changes
        run: git pull origin main

      # Gera o arquivo SVG da animação da cobra
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Adiciona os arquivos gerados
      - name: Add generated files
        run: git add dist/

      # Commit dos arquivos gerados
      - name: Commit changes
        run: git commit -m "Update snake animation"

      # Push para o branch principal
      - name: Push changes
        run: git push origin main

